version: 2
jobs:
  build:
    docker:

      - image: circleci/python:3.7.4

    working_directory: ~/repo

    steps:
      # checkout project code into working directory (~/repo)
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools
            pip install -r requirements.txt # is this right ??

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install protobuf
          command: |
            curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
            unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
            sudo mv protoc3/bin/* /usr/local/bin/
            sudo mv protoc3/include/* /usr/local/include/

      - run:
          name: compile protobuf
          command: ./scripts/compile-proto.sh

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest test.py

      - run:
          name: make graphs
          command: |
            mkdir graphs
            python make_graphs.py graphs

      - store_artifacts:
          path: graphs

      - store_artifacts:
          path: logs
